kiwix-build.py
patches/ctpp2_dll_export_VMExecutable.patch
patches/ctpp2_mingw32.patch
patches/ctpp2_win_install_lib_in_lib_dir.patch
patches/icu4c_fix_static_lib_name_mingw.patch
patches/xapian_pkgconfig.patch

This branch NEEDS newer version of meson/ninja to cross-compile from Fedora to Windows.

Cross compilation windows

---

kiwix-build.py

add support for `--no_cert_check` flag, trying to solve #9

Support flag --no_cert_check

---

dependencies.py
dependency_utils.py
kiwix-build.py

Add support for zimwriterfs in kiwix-build.py

Zimwriterfs

---

.travis.yml
dependencies.py
kiwix-build.py
travis/compile_all.sh
travis/deploy.sh

Let's prepare the dependencies archives for other projects.

Prepare deps

---

kiwix-build.py

Please check and approve this change to add the automake and related packages so they're added as debian packages.

Added the Debian automake package to the dependencies.

---

dependencies.py
kiwix-build.py
templates/meson_cross_file.txt

Now that the search is in zimlib we have to reflect it in our
configuration :
- Zimlib depends of Xapian
- Kiwixlib doesn't depend of Xapian anymore.

Update dependencies tree.

---

kiwix-build.py

The target (`platform_info.build`) is not enough to get a correct
cross_env. For android apk, the target is always "android" but we want
different cross_env depending of the target arch.
The `platform_info` already know for which arch we are building so
let's make platform_info generate the cross_env directly.

Remove CROSS_ENV global variable (and fix android compilation).

---

dependencies.py
dependency_utils.py
kiwix-build.py
utils.py

Depends on https://github.com/kiwix/kiwix-android/pull/123

Android custom apk

---

kiwix-build.py
templates/meson_cross_file.txt

Kiwix-lib need to know want is the android abi to copy the lib in the
right directory.
Needed by https://github.com/kiwix/kiwix-lib/pull/55
Related to https://github.com/kiwix/kiwix-android/issues/151

Set the android_abi variable in the meson_cross_file.txt

---

build_custom_app.py
dependencies.py
travis/make_release.sh

First commit of this PR supersedes #65

Fix custom app

---

.travis.yml
dependencies.py
dependency_utils.py
kiwix-build.py
travis/compile_all.sh

Nightly will also be publish alongside with other nightly's.
Fixes #89 and #90

Also compile zim-tools and zimwriterfs in the CI.

---

travis/compile_all.py

And travis is using python 3.4 :/

`write_text` method exists only on python 3.5.

---

travis/compile_all.py

Fix small typos in the armhf name.

---

travis/compile_all.py

This way, deploy.sh can upload the archive at the right place.

[TRAVIS] Copy release archive in the right subdirectory.

---

MANIFEST.in
kiwixbuild/dependencies.py

This is needed to patch the sources.

Correctly include the patche files.

---

kiwixbuild/__init__.py
kiwixbuild/toolchains/linux_i586.py

We need a to compile binaries without sse instructions
(https://github.com/kiwix/kiwix-build/issues/94#issuecomment-376814014)

Compile i586 without sse instructions.

---

.travis.yml

Do not build android mips in travis in case of cron or pull_request.

---

kiwixbuild/__init__.py

Make kiwix-build install libtool.

---

travis/compile_all.py

See commit https://github.com/kiwix/kiwix-tools/commit/7c254544

Last version of kiwix-tools doesn't have a kiwix-install binary.

---

kiwixbuild/builder.py

Toolchains are not really a deps, they have to be build everytime.

Add toolchains steps even if we are building with `--build-nodeps`.

---

.travis.yml
kiwixbuild/packages.py
travis/Dockerfile
travis/compile_all.py

Keep default travis env for everything else.

Use Docker to build kiwix-desktop only.

---

kiwixbuild/builder.py
travis/compile_all.py

- Correctly make dist.
- zimwriterfs is now using meson, we don't need a special case.

[TRAVIS] Fix release dist.

---

kiwixbuild/dependencies/kiwix_custom_app.py
kiwixbuild/platforms/android.py

This is forgotten dependency. Not updated when we moved to multi-arch
build.
Now, it is fixed.

Fix compilation of kiwix-custom-app.

---

travis/compile_all.py

kiwix-build add `_release` postfix, not the version number.

Fix the src path of kiwix-desktop when doing release.

---

appveyor/deploy.sh
travis/deploy.sh
travis/deploy_apk.sh
travis/make_release.sh

On new server, the user `nightlybot` as been renamed to `ci`.

Update upload script to new server user "ci".

---

kiwixbuild/dependencies/kiwix_lib.py
kiwixbuild/flatpak_builder.py

Mainly to fix review comments of flathub/flathub#768

Fix flatpak

---

requirements_build_custom_app.txt

Update Python request to 2.20.0

---

kiwixbuild/platforms/android.py
kiwixbuild/platforms/armhf.py
kiwixbuild/platforms/i586.py
kiwixbuild/platforms/ios.py
kiwixbuild/platforms/win32.py

This is needed to have kiwix-lib find the `mustache.hpp` include when
cross compiling.

Add the include dir in the meson_cross_file.

---

kiwixbuild/versions.py

Relates to https://github.com/kiwix/kiwix-android/pull/930/

Update Gradle Version

---

appveyor/install_xapian.cmd
kiwixbuild/dependencies/xapian.py
kiwixbuild/patches/xapian_fix_include_errno.patch
kiwixbuild/versions.py
travis/compile_all.py

Use xapian 1.4.10 insteal of 1.4.7

---

.travis.yml
travis/deploy.sh

- Also deploy when we have DESKTOP_ONLY (because docker image doesn't
deploy anymore)
- Correctly get the list of git directory to push.

Fix deploy

---

kiwixbuild/dependencies/xapian.py

Disable Xapian remote backend

---

kiwixbuild/dependencies/gradle.py
kiwixbuild/versions.py

https://github.com/kiwix/kiwix-android/pull/1140

Gradle Upgrade

---

kiwixbuild/dependencies/libzim.py
kiwixbuild/versions.py

Also build libzim and zim-tools because build fails the last time.

New version of kiwix-lib and kiwix-tools.

---

kiwixbuild/dependencies/kiwix_lib.py
scripts/upload_kiwix_lib_android_to_bintray.py
travis/compile_all.py

Now we generate the pom file in kiwix-lib side, we don't need to generate
it ourselves.

Do not generate the pom file in kiwix-build.

---

README.md

Update Readme.MD, correct spelling error

---

.github/ci_images/bionic_builder.dockerfile
.github/ci_images/f30_builder.dockerfile
.github/ci_images/f31_builder.dockerfile
.github/ci_images/focal_builder.dockerfile
.github/ci_images/xenial_builder.dockerfile
.github/scripts/common.py
.github/scripts/compile_all_deps.py
.github/scripts/ensure_base_deps.py
.github/scripts/upload_failure_logs.sh
.github/workflows/base.yml
.travis.yml
kiwixbuild/platforms/android.py
kiwixbuild/platforms/armhf.py
kiwixbuild/platforms/i586.py
kiwixbuild/platforms/ios.py
kiwixbuild/platforms/win32.py
kiwixbuild/templates/meson_cross_file.txt
setup.py
travis/xenial_builder.dockerfile

CI running with github-action use the user `runner`.
Do like github-action to be able to reuse the base_dep archive.
Use name `base_deps2_*` instead of `base_deps_*` to avoid comflict with
current CI.

Use github action to build base deps of kiwix-build.

---

.github/scripts/common.py
kiwixbuild/__init__.py
kiwixbuild/builder.py
kiwixbuild/dependencies/base.py
kiwixbuild/utils.py
travis/compile_all.py

We simply do a `git merge --ff-only` instead of a `git reset`. This way:
- No change on the local repository
=> update to `remote/master`
- If you switch branch and local branch is behind `remote/master`
=> fast forward to `remote/master`
- If you switch branch and branches diverge
=> No update of the directory
- On branch master (or a branch behind `origin/master`) with compatible
change in the working tree.
=>  update of the directory
- On branch master (or a branch behind `origin/master`) but incompatible
change in the working tree.
=>  No update.
This way, sources are keep up-to-date as far as possible.

No git update

---

kiwixbuild/dependencies/base.py
kiwixbuild/flatpak_builder.py

Revert 10c767e8ce933f3fe3d26ed9188cd517c79d8808

Build zstd in flatpak.

---

.github/ci_images/bionic_builder.dockerfile
.github/ci_images/f31_builder.dockerfile
.github/ci_images/focal_builder.dockerfile
.github/ci_images/xenial_builder.dockerfile
.github/workflows/ci.yml
.travis.yml
kiwixbuild/buildenv.py
setup.py
travis/xenial_builder.dockerfile

`platform.linux_distribution` is deprecated.
Fix #415

Use distro module to detect the distribution name.

---

kiwixbuild/dependencies/base.py
kiwixbuild/dependencies/docoptcpp.py

Now kiwix-build uses a commit id that has pkgconfig for docopt

Gitclone for docopt dependency

---

appveyor/install_kiwix-desktop.cmd

fix https://github.com/kiwix/kiwix-desktop/issues/373

Remove kiwix-desktop console for release versions

---

kiwixbuild/dependencies/libmicrohttpd.py
kiwixbuild/versions.py

Fixes https://github.com/kiwix/kiwix-lib/issues/324
Depends on https://github.com/kiwix/kiwix-lib/pull/377

Upgrade libmicrohttpd to 0.9.71

---

.github/workflows/ci.yml
.gitignore
kiwixbuild/platforms/ios.py

Add UIKit for macOS (aka project catalyst) as a build target. 
`kiwix-build --target-platform iOS_Mac_ABI kiwix-lib`
@mgautierfr could you help me add a build in CI?

Catalyst abi

---

kiwixbuild/dependencies/zim_tools.py

See https://github.com/openzim/zim-tools/pull/206#issuecomment-772853701

zim-tools needs newly Mustache

---

kiwixbuild/dependencies/xapian.py

Required for kiwix/kiwix-lib#460

Enable inmemory backend in xapian

---

.github/ci_images/bionic_builder.dockerfile
.github/scripts/common.py
.github/workflows/ci.yml
.github/workflows/releaseNigthly.yml
appveyor/install_kiwix-desktop.cmd
kiwixbuild/dependencies/base.py
kiwixbuild/dependencies/kiwix_desktop.py
kiwixbuild/flatpak_builder.py
kiwixbuild/versions.py

Update bionic docker image to use qt 5.15 instead of default qt version.

---

.github/ci_images/bionic_builder.dockerfile
appveyor/package_kiwix-desktop.sh
kiwixbuild/dependencies/flatpak.py
kiwixbuild/platforms/flatpak.py
kiwixbuild/versions.py

Fix different issue with compilation with qt 5.15

---

kiwixbuild/buildenv.py
kiwixbuild/dependencies/base.py
kiwixbuild/dependencies/flatpak.py
kiwixbuild/dependencies/libkiwix.py
kiwixbuild/packages.py
kiwixbuild/platforms/win32.py

Also fix compilation of libkiwix for android on the CI.

Various fix on kiwix-build (mainly for last fedora)

---

.github/workflows/ci.yml
.github/workflows/releaseNigthly.yml

Python 3.6 is not available anymore.

Use python 3.8 on macOS CI

---

appveyor/apply_patch.sh
appveyor/install_xapian.cmd
appveyor/install_zlib.cmd
appveyor/install_zstd.cmd
kiwixbuild/dependencies/zlib.py
kiwixbuild/dependencies/zstd.py
kiwixbuild/versions.py

Fixes https://github.com/kiwix/libkiwix/issues/737

Use zlib 1.2.12

---

kiwixbuild/versions.py

Update kde and qtwebengine to last Platform version.

---

.github/ci_images/bionic_builder.dockerfile
.github/scripts/build_projects.py
.github/scripts/build_release_nightly.py
.github/scripts/common.py
.github/scripts/compile_all_deps.py
kiwixbuild/dependencies/libzim.py
kiwixbuild/packages.py

Publish libzim for android

---

.github/scripts/common.py
.github/workflows/releaseNigthly.yml

altool has been deprecated in favor of notarytool

Use notarytool to notarize on macOS

---

.github/scripts/build_release_nightly.py
.github/scripts/common.py

Fix #543 
Please not that by definition, Nightly&Release workflow is not run on PR. So check is useless here. Review carefully :)

Fix release detection

---

.github/scripts/build_projects.py
.github/scripts/build_release_nightly.py
kiwixbuild/dependencies/libkiwix.py
kiwixbuild/platforms/native.py

Fixes https://github.com/kiwix/libkiwix/issues/845

Compile libkiwix on native_mixed

---

README.md

This part of the features of this repository was missing a documentation

Add env container images documentation

---

.github/scripts/common.py

They are useless and they use precious disk space. Fix #567

Remove `share/doc` and `share/man` from the deps archive.

---

.github/workflows/container.yml

Fix broken container images release

Use latest container images

---

.github/workflows/releaseNigthly.yml

Fix release workflow

---

.github/scripts/build_projects.py
.github/scripts/build_release_nightly.py
.github/scripts/common.py
.github/workflows/ci.yml
.github/workflows/releaseNigthly.yml
kiwixbuild/platforms/android.py
kiwixbuild/platforms/armhf.py
kiwixbuild/platforms/base.py
kiwixbuild/platforms/i586.py
kiwixbuild/platforms/ios.py
kiwixbuild/platforms/win32.py

Add macOS_arm64_mixed platform.

---

.github/scripts/build_projects.py
.github/scripts/build_release_nightly.py

We don't want to compile zim-tools on macOS_arm64_dynamic.

Fix compilation on CI macOS

---

.github/workflows/ci.yml
.github/workflows/container_images.yml
.github/workflows/releaseNigthly.yml
README.md
ci_images/focal_builder.dockerfile
kiwixbuild/versions.py
scripts/create_kiwix-desktop_appImage.sh

Move all our CI/CD to focal instead of bionic

---

kiwixbuild/dependencies/xapian.py
kiwixbuild/patches/xapian_win32.patch
kiwixbuild/versions.py

New version of xapian 1.4.22

---

.github/scripts/build_projects.py
.github/workflows/releaseNigthly.yml

Build tools on macos

---

README.md

Attempt to better explain/document what Kiwix Build does and how to use it.

Add explicit outcomes in README

---

.github/scripts/common.py
.github/scripts/upload_failure_logs.sh

Attempt to speed-up scp uploads

Use a scp cipher which goes faster

---

.github/scripts/build_definition.py
.github/scripts/build_projects.py
.github/scripts/build_release_nightly.py
.github/scripts/common.py
.github/scripts/compile_all_deps.py
.github/workflows/ci.yml
.github/workflows/releaseNigthly.yml

Move the definition of what to build in a table.

---

.github/scripts/build_definition.py
.github/scripts/common.py
.github/workflows/ci.yml
.github/workflows/releaseNigthly.yml
kiwixbuild/dependencies/__init__.py
kiwixbuild/dependencies/arm_musl.py
kiwixbuild/platforms/__init__.py
kiwixbuild/platforms/arm_musl.py

I have to mention that adding a new cross compiled target never seems so simple.

Add target aarch64_musl_*

---

kiwixbuild/dependencies/armhf.py
kiwixbuild/platforms/armhf.py
kiwixbuild/versions.py

Move back to the old toolchain for aarch64

---

kiwixbuild/versions.py

Publish libzim 9.0.0 source tarball and binaries

Release libzim 9.0.0

---

kiwixbuild/dependencies/aria2.py
kiwixbuild/versions.py

Bump-up aria2 to 1.37.0

---

kiwixbuild/dependencies/libkiwix.py
kiwixbuild/dependencies/libzim.py

Build libzim and libkiwix in debug mode on android.

---

.github/scripts/build_definition.py

Publish CI libkiwix's dependencies for iOS cross-compilation

---

kiwixbuild/versions.py

This rebuild is for android arm compilation fix.

Rebuild libzim and libkiwix.

---

kiwixbuild/dependencies/base.py
kiwixbuild/dependencies/kiwix_desktop.py
kiwixbuild/flatpak_builder.py
kiwixbuild/versions.py

Fix https://github.com/flathub/org.kiwix.desktop/issues/10
Fix https://github.com/kiwix/kiwix-desktop/issues/961

Update flatpak build

---

actions/dl_deps_archive/dist/index.js

https://github.com/kiwix/kiwix-build/pull/716 forget about `dist/index.js`

Update dl_deps_archive dist

---

.github/scripts/build_definition.py
.github/scripts/common.py
.github/workflows/ci.yml
kiwixbuild/buildenv.py
kiwixbuild/dependencies/all_dependencies.py
kiwixbuild/dependencies/base.py
kiwixbuild/dependencies/kiwix_desktop.py
kiwixbuild/versions.py
scripts/package_kiwix-desktop_windows.py

This PR finally build (and package) kiwix-desktop for Windows using Github CI.
Missing (for next PR):
- Removing appveyor build
- Signing kiwix-desktop binary

Build kiwix-desktop on Windows github CI

---

.github/scripts/build_definition.py
.github/workflows/releaseNigthly.yml
scripts/package_kiwix-desktop_windows.py

Setup kiwix-destkop signature on Windows.

---

.github/scripts/build_definition.py

Compile zim-tools and kiwix-tools on Windows github CI.

---

kiwixbuild/versions.py

For https://github.com/kiwix/libkiwix/issues/1081

Release libkiwix 14.0.0

---

.github/workflows/cd.yml

Fixes #770
Executing the nightly 2 hours after the CI

Execute nightly at 3AM (in place of 1AM)

---

kiwixbuild/versions.py

Should fix #785
Should have been done in #784.

Bumped version of kiwix-desktop to 2.4.0

---

kiwixbuild/dependencies/aria2.py
scripts/create_kiwix-desktop_appImage.sh

All dependencies should be copied/stored on our drive

Aria2c has to be stored on dev.kiwix.org

---

kiwixbuild/dependencies/aria2.py
scripts/create_kiwix-desktop_appImage.sh

Use aria2c 1.37.0 in kiwix-desktop appimage

---

.github/scripts/common.py

Fix compilation of Kiwix Desktop 2.4.0 on Flathub

---

kiwixbuild/dependencies/zim_testing_suite.py
kiwixbuild/versions.py

Update zim-testing-suite to 0.7.0

---

kiwixbuild/dependencies/zim_testing_suite.py
kiwixbuild/versions.py

This is the kiwix-build counterpart of openzim/zim-testing-suite#14

Update zim-testing-suite to 0.8.0

---

kiwixbuild/versions.py

... and make a new build of libzim 9.3.0

Relase zim-tools 3.6.0

---

kiwixbuild/dependencies/mustache.py

Move Mustache source tarball from GitHub to dev.kiwix.org

Use local mustache archive

---

kiwixbuild/dependencies/gumbo.py
kiwixbuild/versions.py

Fixes https://github.com/openzim/zim-tools/issues/331

Latest Gumbo parser 0.13.1 compilation with Meson

---

.github/scripts/common.py

Fixed the contents of the WASM build package

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Fixes #830
Attempting to update to macOS 14 and XCode 16.1 on the CI/CD pipelines.

Update to macOS 14 and XCode 16.1

---

.github/workflows/cd.yml

Recreate base deps using Qt6 library (where this is possible)
Related to #594

Kiwix Desktop CI/CD using Qt6

---

kiwixbuild/dependencies/zlib.py
kiwixbuild/versions.py

Use zlib-1.3.1 in place of zlib-1.2.12

---

scripts/create_kiwix-desktop_appImage.sh

AppImageKit releases have been obsoleted

---

.github/scripts/build_definition.py
.github/workflows/cd.yml
.github/workflows/ci.yml
kiwixbuild/dependencies/icu4c.py
kiwixbuild/dependencies/tc_musl.py

x86-64_musl is now built on jammy

---

kiwixbuild/configs/android.py

Related to https://github.com/kiwix/java-libkiwix/issues/119

Force memory pagesize to 16KB on Android
