- kiwix-build.py
The `context` argument has been add to python 3.4.3 version.
We must not use it for older version.
Fix #31
> Use the `urllib.request.urlopen`'s `context` argument only if available.

- travis/compile_all.sh
Relative path is a bad idea, it fails if we change the current directory.
(And it actually fails with the scp)
> Use absolute path to reference ssh key.

- patches/ctpp2_mingw32.patch
It seems that last meson version (0.40.0) do not pass cross compilation
extra_args to compiler when checking for headers.
Thus, the kiwix-lib check for ctpp2 headers fails because the WIN32
define is not present. So kiwix-lib is compiled without CTPP2 but
kiwix-tool compile as if kiwix-lib where compile with CTPP2 and fails.
By making CTPP2 headers check for `__WINGW32__` we workaround this problem.
I don't know if this is a bug in meson, ctpp2 or kiwix-lib but this small
fix allow to compile correctly with last meson version.
> Update ctpp2 patches to handle mingw32 compilation with meson 0.40.0

- dependencies.py
- dependency_utils.py
- kiwix-build.py
- patches/ctpp2_compile_ctpp2c_static.patch
Now that kiwix-lib compile ctpp2 template, we also need ctpp2c binary.
> Install ctpp2-utils to have ctpp2 compiler installed.

- dependencies.py
- patches/ctpp2_compile_ctpp2c_static.patch
As we are compiling `ctpp2c` in static native and install it with a simple
`cp`, the default compilation of ctpp2 library should not install ctpp2c.
Else we would have a wrong `ctpp2c` in the path and later compilation will
fail.
> [CTPP2] CMake should not install ctpp2c.

- dependencies.py
kiwix-lid doesn't need them on Darwin (as on Android).
Depends on kiwix/kiwix-lib#81
> Do not try to compile ctpp2 and ctpp2c on Darwin.

- dependencies.py
We don't need it as it is available is "standard" sdk.
> Do not compile uuid on macos or ios

- dependencies.py
- travis/install_extra_deps.sh
I don't know why, but the travis build doesn't work since few days.
It seems that pip3 cannot install in `/usr/local` anymore.
Probably related to last travis change* as a lot of people seems to have
problem with this update and python (even if this is not the same problems)
Anyway, we should not install a dependencies in global environment without
a sudo. Let's install the pip3 dependencies for the user only.
[*] https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/
> Fix installation of meson and pillow (pip3) in travis.

- dependency_utils.py
- kiwix-build.py
- templates/meson_android_cross_file.txt
To run unit-test (meson) on cross-compilation, we need a wrapper to run
the binary (wine, qemu, ...), but:
- We have no emulator for android (we have one for the system, but we can't
simply run a binary)
- With dynamic compilation, it seems pretty complex to configure them
correctly.
- For mingw32 compilation, `wine` need to be correctly configured to
find dll from the system mingw32 installation.
> Run meson test when possible.

- kiwix-build.py
This file is exported in CI archive for other projects.
If we change its name, it will not be exported and other projects will
break.
> Avoid rename the meson cross compilation file.

- kiwix-build.py
- travis/install_extra_deps.sh
`mesontest` command is deprecated since meson 0.42.0 and broken with last
release (0.44.0) (see mesonbuild/meson#2761).
Fix #97.
> Stop using the deprecated (and broken) `mesontest`.

- dependencies.py
- patches/icu4c_noxlocale.patch
Last version of glibc 2.26 has removed the `xlocal.h` file.
(https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27)
We cannot use last version of icu4c (60.1) because it used a feature not
yet exported in mingw32 releases.
So we need to backport a patch for this.
Fix #110
> Backport icu4c patch to not include `xlocale.h`

- travis/compile_all.py
The archives will be extracted in the right directory. We need to store
relative paths.
> Files in the deps archive must not be absolute path.

- .travis.yml
In case of tag push, travis will trigger a build but will set
TRAVIS_BRANCH to the tag name, not "master".
So by default, the deploy script will be skipped in case of tag push.
There is a option "tags: true" to deploy on tag push. But it will run
deploy script ONLY on tag push, not on cron build.
So we need to set TRAVIS_TAGS to something if we are doing a cron build
to allow travis run the deploy script.
> We must run the deploy command even on tag push.

- .travis.yml
- dependencies.py
- dependency_versions.py
- kiwix-build.py
- patches/libaria2_android.patch
libaria2 needs a lot of dependencies to handle all protocol.
So this is a basic compilation of libaria2 :
No tls(https), no metalink and no bit-torrent.
> Add dependency libaria2.

- .travis.yml
Build only if the travis event is not a push (pull_request, cron, ..)
or we are pushing a tag (to build releases).
> Do not do unecessary build.

- travis/compile_all.py
- travis/deploy.sh
The names of archives were inconsistent, rename them to a more consistent
scheme.
> Publish nightly and release archive using the right name.

- .travis.yml
- travis/compile_all.py
- travis/deploy.sh
The directory is create by simply copying the full directory instead of
individual files.
> Create "date" directory when deploying nightly build.

- kiwixbuild/dependencies/icu4c.py
- kiwixbuild/patches/icu4c_build_config.patch
- kiwixbuild/versions.py
- Disable icuio and layoutex.
- Hardcode UTF8 as charset (we always use utf8 and hardcoding him improve
performances)
- Do not include default utf headers
- Do not use `using namespace icu`
See http://source.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild
for more information about options.
Increment base dependencies version as we are compiling icu differently.
> Better compilation of icu4c.

- .travis.yml
The deployement is already made in the Docker.
"Classic" deploy will fail because there will be no archive to deploy.
> Do not deploy on native_dyn linux platform.

- .travis.yml
- kiwixbuild/versions.py
We build with gcc-5 because of zimSplit using ofstream.swap method.
Latest version of zimSplit doesn't use it anymore so let's compile
everything with default gcc.
See openzim/zim-tools@a9596098391d04de56a7b97f980ed88c60bfc507
> Do not build with gcc-5.

- travis/compile_all.py
QtWebEngine is not compatible with static compilation so we should not
try to compile kiwix-desktop on native_static.
> Do not try to compile kiwix-desktop on native_static.

- kiwixbuild/dependencies/icu4c.py
- kiwixbuild/versions.py
SVN checkout can be pretty long to do (especially if icu serveur is pretty
slow).
By downloading an archive on our own server, we avoid a spending too many
time downloading.
The archive is a simple targz of the SVN checkout.
> Get icu sources from an archive instead of svn.

- .travis.yml
Is a contributor do a PR from its own repository, we will try do decrypt
the key but fail because secret env var are not available.
We need the secret key only if we do a deployement and the deployement is
done only for a tag or a cron job.
> Try to decrypt the secret key only if we will do a deployement.

- kiwixbuild/utils.py
- travis/compile_all.py
Compiling all dependencies for all archs takes a too long time for travis.
By downloading the cache of specific android arch, we avoid to recompile
them.
> [TRAVIS] Try to use arch specific base_deps when build android multi arch.

- travis/compile_all.py
As we now move to multi-arch build, we may have things compiled natively
or "neutral" (as toolchains). So we cannot use the BASE_DIR as
relative_path because BASE_DIR is arch dependent.
> [TRAVIS] Allways use $HOME as relative path in dependencies archives.

- appveyor/install_kiwix-desktop.cmd
The `windows` branch has been merge. We should directly use `master` now.
> [AppVeyor] No windows branch for kiwix-desktop.

- appveyor/package_kiwix-desktop.sh
AppVeyor may update minor version of Qt and change `5.11.0` to `5.11.1`.
If we use the path with the full version, it will break in the futur.
AppVeyor install a link `5.11` pointing to the last version, so let's use
it.
> Fix the path of AppVeyor Qt to be minor version independent.

- appveyor.yml
- appveyor/install_icu.cmd
- appveyor/package_kiwix-desktop.sh
windeployqt modify the executable, so we must sign it after.
> Sign the application after windeployqt.

- kiwixbuild/dependencies/libzim.py
Android devices are low memory devices, use last libzim compilation option
to avoid copy/mmap index header in memory.
Depends of https://github.com/openzim/libzim/pull/178
> Do not use buffered header on android.

- travis/compile_all.py
The building Windows zip decompressor handles only DEFLATED.
> Use the ZIP_DEFLATED compression when creating zip archive.

- kiwixbuild/versions.py
- travis/compile_all.py
We new release of a project is made, projects dependending of it are
rebuild and republish to keep the binaries up-to-date.
To avoid overwrite the already build archives and silent the fact that
new archives are available, we need to have a extra build version.
`extra_build_versions[project]` has to be set each time a dependency of
`project` is bump but the project version has not changed.
If the `project` version changes, the `extra_build_versions[project]`
has to be cleared.
If a "end project" is updated, we will still rebuild (and publish)
the other projects. However, has the other projects doesn't depends of
a the bump project, the build should be the same, without improvement.
This is not perfect but at least, we do not hide new important build.
See kiwix/kiwix-tools#222
> Do not overwrite release build archives.

- .travis.yml
- appveyor.yml
- appveyor/create_cache.sh
- appveyor/install_aria2.cmd
- appveyor/install_kiwix-desktop.cmd
- appveyor/install_libcurl.cmd
- appveyor/package_kiwix-desktop.sh
- appveyor/setup_from_cache.cmd
- kiwixbuild/dependencies/libcurl.py
- kiwixbuild/packages.py
- travis/Dockerfile
On ubuntu, the libcurl package is compiled with libkrb (kerberos).
However, no libkrb5.a is provided and so, we cannot link statically.
As we are not using kerberos, we can (and must) compile ourselves libcurl.
For now we are not using ssl, so lets compile without ssl and don't care
about openssl/gnutls/...
> Force the build of libcurl instead of using system one.

- travis/compile_all.py
`libzim.so` is a symlink to `libzim.so.4`, who is also a symlink to
`libzim.so.4.0.4`.
> We need to deploy the real lib, not the symlink to it.

- travis/compile_all.py
As we are exporting libzim, we also need to export header files.
So now, we are using glob to get the list of file to add to the archive.
Fix openzim/libzim#199
> Better of export of file (release and nightly)

- kiwixbuild/dependencies/base.py
- kiwixbuild/dependencies/icu4c.py
- kiwixbuild/dependencies/kiwix_desktop.py
- kiwixbuild/dependencies/pugixml.py
- kiwixbuild/dependencies/xapian.py
- kiwixbuild/dependencies/zlib.py
- kiwixbuild/platforms/android.py
- kiwixbuild/platforms/armhf.py
- kiwixbuild/platforms/ios.py
- kiwixbuild/templates/meson_cross_file.txt
- kiwixbuild/versions.py
- travis/compile_all.py
- Dependency are installed "striped".
- Our project are build "debugoptimized" by default and "release" when
building release instead of "debug"
We need to update the `base_deps_meta_version` as we are changing how
dependencies are compiled.
> Build in release mode.

- .travis.yml
- scripts/create_kiwix-desktop_appImage.sh
Now that issue probonopd/linuxdeployqt#340 is fixed with a new option
`-unsupported-allow-new-glibc`, we can revert commit 4329629f
> Fix creation of appimage.

- travis/compile_all.py
The win platform starts with `win32_`, not `win-`.
> Fix creation of win32 archives.

- kiwixbuild/flatpak_builder.py
dictionnaries aren't ordered with python 3.5, OrderDict() fixes that.
> fix unordered flatpak's manifest

- travis/appimage_builder.dockerfile
EOL for artful is july 2018.
It seems that now, apt repository has been shutdown for artful.
It is time to move to a more recent ubuntu version.
Bionic is the oldest release for which QtWebEngine has been packaged.
> Move from artful to bionic.

- scripts/create_kiwix-desktop_appImage.sh
`verbose=3` is too verbose for travis. Travis kill our job because the log
is too long.
> Make the appimage creation less verbose.

- travis/deploy.sh
The git repositories to upload are in the $EXPORT_DIR/GIT.
So we need to move there before try to push them.
> Fix deployement of git repositories.

- kiwixbuild/versions.py
We also rebuild kiwix-desktop because last build's deployment fails.
> New version of zimwriterfs.

- kiwixbuild/versions.py
update to sdk tools used in newest android studio 3.4.1 and gradle build tools
> update android sdk tools to 26.1.1

- kiwixbuild/platforms/ios.py
Fix #323
Looks like this is the only line I need to change to make targeting iOS compile work on macOS 10.14. 
I do however have to do what this ticket said to get curl working: https://github.com/curl/curl/issues/3189
Speaking of curl. Why does libkiwix need curl? Kinda ironic considering what libkiwix does is offline viewing...
> fix for macOS cross build targeting iOS

- .github/workflows/base.yml
- kiwixbuild/dependencies/base.py
- kiwixbuild/dependencies/libmicrohttpd.py
- kiwixbuild/versions.py
there's a weird bug on macOS (catalina as least) with version `0.9.69` of `libmicrohttpd`.
It compiles and links properly but the server can never be started, failing in `MHD_start_daemon`: it always returns false and when enabling debug, the message simply says `Failed to create socket for listening`. Depending on version, details are either `file not found` or `undefined: 0`.
I tested many different combinations of versions and compile flags but ultimately settled with just using older version `0.9.63`. I haven't tested on other platforms but hope it can be replaced as is.
Here's the changelog in-between:
```
Sun 15 Dec 2019 02:12:02 PM CET
Fix send() call (affects Mac OS X). #5977 -CG/fbrault
Releasing libmicrohttpd 0.9.69. -CG
Fri 29 Nov 2019 11:22:25 PM CET
If application suspends a …
```
> switch to older version of libmicrohttpd

- kiwixbuild/platforms/android.py
- kiwixbuild/platforms/base.py
- kiwixbuild/platforms/i586.py
- kiwixbuild/platforms/ios.py
Even if we use different template for different platform, we must
always use the same cross_file name.
> Always write the cross_file using the same name.

- kiwixbuild/dependencies/base.py
- kiwixbuild/dependencies/kiwix_desktop.py
- kiwixbuild/dependencies/uuid.py
- kiwixbuild/dependencies/xapian.py
- kiwixbuild/versions.py
This will build all Make, CMake, QMake dependency being build with -O3.
So all our dependencies will be build with -O3.
Our project (meson) are already build in release when needed.
kiwix-desktop should be build optimized in case of release but we need
to handle it correctly. At least not build in O3 per default as it may
break debug.
> Build all make based dependency using -O3 option.

- .github/scripts/common.py
- kiwixbuild/dependencies/base.py
- kiwixbuild/dependencies/kiwix_desktop.py
- kiwixbuild/dependencies/kiwix_lib.py
- kiwixbuild/dependencies/kiwix_tools.py
- kiwixbuild/dependencies/libzim.py
- kiwixbuild/dependencies/zim_tools.py
- kiwixbuild/dependencies/zimwriterfs.py
- kiwixbuild/utils.py
- travis/compile_all.py
We were assuming that meson project correspond to our projects and so we
were always building them, even if they were already compiled.
(This way, a simple `kiwix-build` is enough to recompile the WIP code of
our project).
However, on the CI, we do not archive the source code/build directory in
the base deps archive. So when we try to compile, the compile step of
meson projects fails because the source are not here.
We have a small workaround for pugixml but as zstd is also meson, it is
time to do something correct.
By default, all projects now try to skip if a build is already present.
Our projects are marked as `force_build` and so, they do not try to skip.
> Fix recompilation of the CI of meson project.

- kiwixbuild/dependencies/qt.py
> Fix qt-everywhere-src-5.10.1.tar.xz URL

- appveyor.yml
- appveyor/apply_patch.sh
- appveyor/install_xapian.cmd
- appveyor/install_zstd.cmd
- kiwixbuild/dependencies/__init__.py
- kiwixbuild/dependencies/all_dependencies.py
- kiwixbuild/dependencies/libzim.py
- kiwixbuild/dependencies/zstd.py
- kiwixbuild/patches/zstd_meson.patch
- kiwixbuild/versions.py
[CI run](https://github.com/kiwix/kiwix-build/actions/runs/67267196) has "succeeded" - the only "failure" for the *Linux (native_desktop)* is a compilation error unrelated to my changes (the same error is found in the [latest CI run on master](https://github.com/kiwix/kiwix-build/runs/547320962))
I downloaded the newly built dependency archive from http://tmp.kiwix.org/ci/deps2_osx_iOS_arm64_libzim.tar.xz and made sure that it contains `libzstd.a`. A successful rerun of the [previously failed CI build](https://github.com/openzim/libzim/runs/548283975) for the zstd branch of openzim/libzim (so that it uses the regenerated dependencies from this change) serves as another proof of correctness of this PR.
Included in this PR is a fix for the xapian compilation failure in the appveyor build …
> Added zstd dependency (fixes #422)

- kiwixbuild/dependencies/__init__.py
- kiwixbuild/dependencies/all_dependencies.py
- kiwixbuild/dependencies/docoptcpp.py
- kiwixbuild/dependencies/zim_tools.py
- kiwixbuild/versions.py
This PR adds the docopt cpp library to the build environment. It will be needed for zimdump.
> Added docopt cpp dependency to zimtools

- .github/workflows/ci.yml
- .travis.yml
- kiwixbuild/__init__.py
- kiwixbuild/platforms/ios.py
The Kiwix for iOS app no longer supports iOS 10, which means we no longer support 32bit devices. (All devices capable of running iOS 11 are 64 bit). I have actually already shipped two versions of the app with libs build in this branch.
I tried to update CI, but it didn't seem to work... Please help.
> iOS remove 32bit builds

- .github/scripts/build_release_nightly.py
- .github/scripts/common.py
- .github/workflows/ci.yml
- .github/workflows/releaseNigthly.yml
- kiwixbuild/platforms/native.py
Fixes #349 by enabling `native_mixed` for OSX in the CI and release.
- release on macOS is limited to libzim
- libzim shared lib is renamed to strip out the build path
- output release name is customized to produce `-macos-` instead of `-linux`
- For this to produce a macOS release, we have to change libzim version to `0` ; included it here but that may not be wanted (66eb4fa)
> Release libzim for macOS in the CI

- kiwixbuild/versions.py
Docopt commit id was updated and therefore we need to force a new build in order to get the latest change (docoptcpp.pc) into the deps2 archive (needed by zim-tools)
> Force compilation of docoptcpp

- .github/workflows/ci.yml
Directly use brew instead of `get-package` action.
`get-package` seems to be broken with some invalid git command.
> Fix macos brew install packages.

- .github/scripts/build_release_nightly.py
- .github/scripts/common.py
- .github/workflows/releaseNigthly.yml
This triggers a `workflow_dispatch` event on the `docker.yml` workflow or the matching
repository for both `zim-tools` and `kiwix-tools` targets that supports it.
@mgautierfr this uses requests as requests is already used in upload_bintray and thus installed in the images used. I had a version using only urllib if you'd prefer.
Also, this is based on the filtering that is already done in the matrix and earlier in the script so it's just triggered after the upload of the binaries but that may not be obvious.
Finally, this just prints on error ; should we raise/fail? How critical is this given it can be triggered manually…
> Trigger docker publish on release

- kiwixbuild/builder.py
Home brew recently deprecated `brew list`, resulting in errors when determining if automake etc. exists:
```
(venv) chrisli@Chriss-Mac-Pro kiwix-build % kiwix-build --target-platform iOS_multi kiwix-lib
[INSTALL PACKAGES]
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
- autoconf : NEEDED
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
- automake : NEEDED
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
- libtool : NEEDED
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
- cmake : NEEDED
```
In this PR, I am updating the subprocess call used to determine if a certain brew formula is installed to …
> Use brew ls --version

- .github/scripts/build_release_nightly.py
- .github/scripts/common.py
- .github/workflows/releaseNigthly.yml
This adds the notarization (see #469) of the libzim binary for macOS during the build.
It it not dependent on RELEASE so it benefits all builds.
It basically does two things:
- sign the build with our Developer ID certificate from Apple.
- Request notarization from Apple for the binary.
At the moment, it concerns only libzim. Might expand that to libkiwix and the zim/kiwix tools
once we start releasing those.
Github Actions prepare the certificate and environment, and signing+request is done in `notarize_macos_build()` (common.py)
It required the following new secrets:
| secret | value |
|---|---|
| `APPLE_SIGNING_CERTIFICATE` | base64 of the P12 certificate |
| `APPLE_SIGNING_P12_PASSWORD` | password for the P12 certificate (we chose that when exporting to P12. Apple doesnt provide P12) …
> Notarizing libzim release for macOS

- .github/workflows/releaseNigthly.yml
We update the time when installing the certificate because there's a timestamp comparison during signing and that prevents signing failures due to clock drifting in the containers.
Updating time using ntp does requires sudo though.
> time update requires sudo

- .github/workflows/releaseNigthly.yml
This is not strictly required but sometimes the time server doesn't respond within the default timeout (5s), making the whole build fail.
This just sets a 60s timeout instead so a slow-response request would still succeed and the build will proceed.
> allow more time for ntp server to respond

- .github/workflows/releaseNigthly.yml
For the past week, the Release&Nightly workflow failed on macOS native_mixed
(but not on native_dyn) when calling ntp to sync clock before signing.
Calling time.apple.com resulted in a DNS error, leading to an error in ntp call
Why this fails on native_mixed is unknown. Maybe because it's being called twice
from the same (I guess) host in a short interleave?
This attempts to fix this by:
- using google's time server instead of Apple's
- correctly setting the timeout param before the server name (although not relevant
for this dns-based error)
- Ignore failures to sync time. We're doing it to minimize chances of unsynched clocks
to fail the signature but this is not absolutely required all the time.
> Change time server in workflow

- appveyor/package_kiwix-desktop.sh
The verisign timestamp server has been deprecated
(see https://stackoverflow.com/questions/65541786/is-the-verisign-timestamp-server-down)
Let's use the new digicert server as told in
https://docs.microsoft.com/en-us/windows/win32/seccrypto/using-signtool-to-sign-a-file
> Use correct timestamp server for signing/dating kiwix-desktop.

- kiwixbuild/dependencies/libzim.py
The source step (install source) always exists.
The `plaformInfo.name` step may not exists
(On mixed target, we build all deps static and the last project dyn)
So the `native_dyn` doesn't exists for `zim-testing-suite`.
> Get the "source" `zim-testing-suite` step.

- .github/workflows/ci.yml
- .github/workflows/releaseNigthly.yml
- kiwixbuild/patches/icu4c_custom_data.patch
- kiwixbuild/versions.py
With language data not put into the ICU package, `icu::Locale::getDisplayLanguage()` doesn't work correctly. This is required by kiwix/libkiwix#553 (see https://github.com/kiwix/libkiwix/pull/553/commits/0198cdafaeddc6fe12a9875f4525effb998f4671).
> Language data is packaged into ICU

- appveyor/package_kiwix-desktop.sh
Recent version of signtools need us to be explicit about the used
algorithm.
This is recommended to use the SHA256 algorithm even if the default
(previous) one was SHA1.
> [WINDOWS][CI] Be explicit about the algorithm used by signtools.

- scripts/create_kiwix-desktop_appImage.sh
Fix AppImage creation script for Fedora34x64:
* use appropriate value for SYSTEMLIBDIR automatically
* do not stop on absence of lib/libmagic.so*
* do not download AppImage tools again on further script runs
> Fix AppImage creation script for Fedora34x64

- scripts/create_kiwix-desktop_appImage.sh
If it is the first time the script is run, $APPDIR doesn't exist, so,
by definition, `$APPDIR/lib` doesn't exists neither.
We must check the library dir in `$INSTALLDIR` which is the "source"
directory for script.
> Fix setting of `SYSTEMLIBDIR` in the appimage creation script.

- .github/workflows/ci.yml
- kiwixbuild/platforms/ios.py
Adding macOS platforms -- Intel(x86) & Apple Silicon(arm64), along with a couple of other things:
- rename the base class to `ApplePlatformInfo` since it is not just about iOS anymore
- update CI to build with the newly created macOS subclasses, removing targets that I don't use (e.g.`native_dyn`)
> macOS Builds (arm64 + x86)

- kiwixbuild/dependencies/libkiwix.py
The java wrapper is using deprecated methods, so we cannot compile with `werror`.
> Do not compile libkiwix on android with werror

- appveyor/package_kiwix-desktop.sh
They are not packaged with windeployqt. We have to package them ourselves.
Until now, we were probably using dll installed by other applications.
Fix kiwix/kiwix-desktop#785
> Package OpenSSL libraries.

- scripts/create_kiwix-desktop_appImage.sh
We have added those libraries to fix kiwix/kiwix-destop#14,
ie allow appimage build on recent system to run on older ones by packaging
the libc and libstdc++ library in the appimage.
But by packaging libstdc++, we force kiwix-desktop to use the packaged one.
On some recent system, the mesa drivers need a recent version of libstdc++ and,
as we are force to use the packaged one, we may use a "old" one.
The workaround forcing a driver was bypassing the problem by forcing a driver
not using a recent libstdc++. But with time, it is more and more difficult
to find one.
This commit means that new appimage generated will works only on equal or
more recent system that the one on which it has been generated.
For now we generate the appimage on Ubuntu bionic (18.04 LTS).
This reverts commit …
> Do not include low level std lib in appimage package

- .github/workflows/releaseNigthly.yml
GITHUB_PAT is needed (and not needed for flatpak)
> Fix workflow triggering in releaseNigthly workflow.

- .github/scripts/common.py
- .github/scripts/compile_all_deps.py
- .github/scripts/ensure_base_deps.py
- .github/scripts/upload_failure_logs.sh
- appveyor/create_cache.sh
- appveyor/deploy.sh
SSH server which was used to receive file uploads (CI, nightly and release) has been
migrated to a new one on a different address.
Username, Key and paths are unchanged.
Most notable changes are the use of `master.download.kiwix.org` as the target in
replacement of `mirror.download.kiwix.org` (although it would still work) and the
Port to which SSH is listening on (30022 instead of 22)
> Target uploads to new dropbox address

- .github/scripts/build_projects.py
- .github/scripts/common.py
- .github/workflows/releaseNigthly.yml
When build_release_nightly calls codesign to sign libzim.7.dylib, it appears to be hanging forever.
What's most likely happening is that Keychain Access is prompting a password request without any possibility to answer, given this is running on the CI.
It's unclear whether Keychain Access wants to confirm codesign can access the certificate or if it is trying to unlock another (System) keychain to find the certificate or key.
This addresses the former.
Fixes #519, tested in [this run](https://github.com/kiwix/kiwix-build/runs/6407707440?check_suite_focus=true)
> Trust codesign using the certificate

- .github/ci_images/alpine_builder.dockerfile
- .github/workflows/ci.yml
- .github/workflows/releaseNigthly.yml
Related to openzim/libzim#709
The PR only enhances the Docker job so that it creates Alpine images that can be used in the openzim/libzim CI. Alpine is not added to the list of configurations used in the kiwix-build CI workflows.
> Added CI image for Alpine

- .github/scripts/build_projects.py
- .github/scripts/build_release_nightly.py
- .github/scripts/common.py
- .github/scripts/compile_all_deps.py
- .github/workflows/ci.yml
- kiwixbuild/buildenv.py
- kiwixbuild/dependencies/__init__.py
- kiwixbuild/dependencies/all_dependencies.py
- kiwixbuild/dependencies/base.py
- kiwixbuild/dependencies/emsdk.py
- kiwixbuild/dependencies/icu4c.py
- kiwixbuild/dependencies/libzim.py
- kiwixbuild/dependencies/lzma.py
- kiwixbuild/dependencies/xapian.py
- kiwixbuild/patches/icu4c_wasm.patch
- kiwixbuild/platforms/__init__.py
- kiwixbuild/platforms/wasm.py
- kiwixbuild/versions.py
Fixes #503
This PR add support to wasm (for libzim).
It it still WIP has I need to check everything is working for other platform (and on the CI)
compilation of  libzim for wasm is working (on my computer) but generated binary has not been tested.
> Libzim wasm compilation

- .github/scripts/build_projects.py
If we try to publish all the time, we will conflict with `Release&Nigthly` workflow as we would pulbish in nigthly directory.
Fix #550
> Publish the CI only if we are on a dev branch.

- kiwixbuild/dependencies/libzim.py
On wasm, we cannot do mmap. We have to do plain read.
Fix openzim/libzim#751
> Fix wasm compilation.

- .github/workflows/ci.yml
- .github/workflows/releaseNigthly.yml
This was recommended because of the deprecated of Node.js 12 on which these old actions version rely on.
> Update GitHub actions to latest version

- kiwixbuild/platforms/ios.py
It seems that on last version of CI envirronement, ios' clang doesnt recognize ios13.0.
Moving to ios 14.0
> Fix the iOsMacABI target in the CI

- kiwixbuild/platforms/wasm.py
- kiwixbuild/versions.py
The default detected libdir is based on the build architecture. On ubuntu, it is `lib/x86_64-linux-gnu` which is obviously not the right directory.
Let's simply use `lib`.
Fix #556
> Install wasm libraries in `INSTALL/lib` directory.

- .github/scripts/common.py
With commit 6181d7bb, we have changed where archives are written. We must addapt our packaging script.
Fix #556
> Correctly package wasm archives.

- .github/scripts/common.py
- kiwixbuild/platforms/armhf.py
We need the aarch64 compiler to let's project build themselves.
> Add the aarch64 toolchains to deps archive.

- .github/scripts/build_projects.py
- .github/scripts/common.py
- .github/workflows/ci.yml
- .github/workflows/container_images.yml
- .github/workflows/releaseNigthly.yml
- ci_images/bionic_builder.dockerfile
- kiwixbuild/dependencies/armhf.py
- kiwixbuild/versions.py
> Build libzim on bionic

- .github/scripts/common.py
We cannot directly push on master. We have to create a pull request. The CI is adapted to push a new branch. The PR has to be created manually.
> Fix publish of kiwix-desktop flatpak.

- .github/workflows/releaseNigthly.yml
The variables are not used in the context of docker triggering.
I prefer set dummy variables instead of use a default value in the code to be sure that the variable are defined when needed.
> Add missing env variable.

- kiwixbuild/versions.py
We don't have a version 13.0.0 for libkiwix.
So the master branch of libkiwix is generating version 12.1.1.
We must use the correct version as we try to fix the rpath on macos and we we don't have the right version, we fail because the lib file doesn't exist.
> Revert back the libkiwix version to 12.1.1

- .github/workflows/releaseNigthly.yml
Use the same strategy that for `CI` workflow:
- By default use a target with `image_variant` to `focal`
- Add include for other image_variant.
> Correctly set the docker image for `x86-64_musl`.

- .github/scripts/build_definition.py
> Fix naming of musl archive for x86_64.

- .github/scripts/compile_all_deps.py
Still publish the deps in the dep_previews directory in case we would like to test it project's CI.
This should avoid conflict (and broken CI) when we try things on kiwix-build CI.
> Publish projects deps in branch-named folder when outside of main

- .github/scripts/build_definition.py
- .github/workflows/ci.yml
- .github/workflows/releaseNigthly.yml
- kiwixbuild/dependencies/libkiwix.py
- kiwixbuild/dependencies/libzim.py
- kiwixbuild/platforms/ios.py
- kiwixbuild/platforms/native.py
This is a redo of #638 that is supposed to be more explicit. It includes:
- now building explicitly on macos13 with Xcode 15.0.1 (for all targets)
- now targeting macOS 12+ and iOS 15+
- removed bitcode as deprecated by Xcode14
- removed `-stdlib` flag as not allowed on Xcode15
- removed `iOSMacABI` that we don't need
Note that I did not rename the targets (contrary to #638). I think it may make sense to but this should be discussed first. It's important kiwix-build maintainers understand clearly the role of each target.
> Apple Platforms updates

- .github/scripts/build_definition.py
> Build zim-tools and kiwix-tools on macos-arm64

- .github/workflows/releaseNigthly.yml
https://github.com/kiwix/kiwix-build/actions/runs/6905519602/job/18788657204 failed due to missing env `OS_NAME`. I thought it was set on the system as other linux jobs don't set it. It's not so it must be passed.
> Add OS_NAME to docker trigger job

- .github/scripts/build_definition.py
- .github/workflows/ci.yml
- kiwixbuild/dependencies/apple_xcframework.py
- kiwixbuild/platforms/ios.py
When we introduced CoreKiwix.xcframework, we made two mistakes:
- We forgot that some devs are on Apple Silicon and did not include arm64 arch for simulator
- We kept the `x86_64-apple-ios` target thinking simulator is a “just” an iOS on x64
This target mistake prevented XCode from finding our lib usable with the Simulator on x64. Not including an arm64 version obviously prevented Silicon-using devs from using the Simulator.
The included libs changes now from
| Name                         | Content                                               |
| ---------------------------- | ----------------------------------------------------- |
| `ios-arm64`                  | All iOS devices are arm64                             |
| `ios-x86_64-simulator`       | Single x64 binary for Simulator …
> CoreKiwix for iOS Simulator

- .github/scripts/build_definition.py
- .github/scripts/common.py
- .github/scripts/ensure_base_deps.py
- actions/dl_deps_archive/.gitignore
- actions/dl_deps_archive/dist/index.js
- actions/dl_deps_archive/index.js
- kiwixbuild/__init__.py
- kiwixbuild/buildenv.py
- kiwixbuild/configs/android.py
- kiwixbuild/configs/base.py
- kiwixbuild/configs/flatpak.py
- kiwixbuild/configs/ios.py
- kiwixbuild/configs/native.py
- kiwixbuild/configs/neutral.py
- kiwixbuild/utils.py
- kiwixbuild/versions.py
Until now, we were publishing deps archives using the `{OS}_{CONFIG}` where OS is the name of the system we are building and CONFIG is how we are building (native/cross...; dyn/static).
Now, we are publishing deps using a name `{TARGET_ARCH}_{dyn/static}` so archives are now independent of the system/config we have used to compile dependencies.
(ie building natively on arm and cross compiling to arm from x86_64 is now using the same name)
On top of that, inside the archive, we were using build dir `BUILD_{CONFIG}`. We now have a option to use `BUILD_{TARGET_ARCH}`.
Note that this option should be used only on CI as we start a new build each time.
On a dev usage when we want to test different config (and especially native vs dyn), this option should not be used as different configs could …
> [CI] Publish dependencies archives for other project using a name based on arch.

- kiwixbuild/__init__.py
- kiwixbuild/buildenv.py
Job `Trigger_Docker` is run in a simple environment not configured. So tools as `ninja` are not installed. But we don't care as we just want to trigger a docker build.
But `common` script now start by asking kiwix-build the build dir. kiwix-build must not fail in this case.
> Do not expect a full working environment when only asking for build dir.

- scripts/create_kiwix-desktop_appImage.sh
Should fix kiwix/kiwix-desktop#1016
`linuxdeployqt` (the tool used for creating the `kiwix-desktop` appimage) doesn't put `libthai.so` into the appimage as that library has caused problems in the past. The entry for `libthai.so` in the respective ["blacklist"](https://raw.githubusercontent.com/probonopd/AppImages/ac4d7b73bd98be7d14644775e9058d09109b2fa5/excludelist) reads:
>     libthai.so.0
>     # Workaround for:
>     # audacity: /tmp/.mount_AudaciUsFbON/usr/lib/libthai.so.0: version `LIBTHAI_0.1.25' not found (required by /usr/lib64/libpango-1.0.so.0)
>     # on openSUSE Tumbleweed
I verified that the fix produces an appimage that works on an **Ubuntu 22.04** system with the `libthai.so*` files temporarily removed from `/usr/lib/x86_64-linux-gnu` whereas the [official release …
> Forcefully adding libthai.so to kiwix-desktop appimage

- scripts/create_kiwix-desktop_appImage.sh
Fixes [#871](https://github.com/kiwix/kiwix-desktop/issues/871)
`libssl.so` and `libcrypto.so` are embedded in the appimage so that it can work on newer systems having a deceptively backward-incompatible version of OpenSSL.
The fix includes patching the `libQt5Network.so` library so that aria2's CA certificate bundle (being included in the appimage before this change) is used as a fallback if no certificates can be found in various locations used for certificate stores on different major Linux distributions. To this end, the AppRun entry point of the AppImage is changed from a symlink to the `kiwix-desktop` binary to a small shell script that creates a temporary symlink at a hardcoded path (`/tmp/cert_bundle_provided_by_kiwix.crt`) pointing to the said certificate bundle within the …
> libssl is embedded in the kiwix-desktop appimage

- .github/scripts/build_definition.py
- .github/workflows/ci.yml
- .github/workflows/releaseNigthly.yml
- kiwixbuild/configs/armhf.py
- kiwixbuild/configs/native.py
- kiwixbuild/dependencies/all_dependencies.py
> Use manylinux container instead of bionic

- kiwixbuild/configs/android.py
As said in [1], unwinder is linked automatically by Clang and shared library must not re-export it.
ndk after r23 (we are using r21) should do this. Else we must take care to not re-export it.
From [2], we should pass the flags `Wl,--exclude-libs,libgcc.a` and `-Wl,--exclude-libs,libunwind.a` to avoid re-export `_Unwind_Resume` methods.
Fix https://github.com/kiwix/kiwix-android/issues/3661
[1] https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding
[2] https://github.com/android/ndk/issues/889#issuecomment-464334469
> Exclude libgcc and libunwind from linked libraries on Android.

- kiwixbuild/versions.py
When releasing libzim and libkiwix, we use config native_mixed with is a mix of static and dynamic linking:
- Dependencies are build as static libraries.
- Released projects (libzim/libkiwix) are build as dynamic libraries, statically linked to dependencies.
This way, we have only one `.so` file which contain all our needed symbols.
However, this logic is "local" to each project.
This mean that libkiwix is linked **statically** to libzim. So libkiwix.so is containing libzim symbols.
But on "java-libkiwix", we are both linking to libzim.so and libkiwix.so. If the version of the (dynamically) used libzim.so is not the same that the version on which we have (statically) linked libkiwix.so, we end with symbols of two different versions being loaded and conflicting.
So let's rebuild libkiwix …
> Rebuild libkiwix 13.1.0

- .github/scripts/common.py
- .github/scripts/ensure_base_deps.py
- actions/dl_deps_archive/index.js
It is a bit of memory waste but a lot of time win (at least on android build)
- Cold android_arm build goes from 51 minutes to 39 minutes
- Cold macos_all_static goes from 1h15 to 1h03
- Warm android_arm build goes from 32 minutes to 26 minutes
- Warm macos_all_static goes from 14 minutes to 8 minutes
> Use gz compression for deps archive.

- .github/workflows/ci.yml
- kiwixbuild/configs/native.py
- kiwixbuild/dependencies/all_dependencies.py
- kiwixbuild/dependencies/icu4c.py
- kiwixbuild/dependencies/libzim.py
- kiwixbuild/dependencies/xapian.py
- kiwixbuild/versions.py
This PR build xapian using meson on Windows.
The version of xapian built is a dev version from https://github.com/openzim/xapian-meson.
It is mostly a 1.4.26 version with patches.
This version as some issues:
- Xapian build using meson on Windows have some tests randomly failing. They are deactivated in https://github.com/openzim/xapian-meson/commit/fb7b5559ee4a2663c2572cca15a279004cbf20a6
- Xapian testing fails on macos_dyn (I suspect it is a 1.4.26 bug, not meson related)
- When libzim use flag `Xapian::Compactor::FULLER` on Windows, xapian crashes. The workaround is to not use this flag.
All those issues have to be fix at a time. But let's advance and merge this unperfect PR.
If you have clues on what happening and how to fix the remaining issues, you are more than welcome !!
> Build Xapian on Windows using meson

- kiwixbuild/dependencies/qt.py
- kiwixbuild/versions.py
> Kiwix-build doesn't try to build qt nor qtwebengine

- kiwixbuild/dependencies/icu4c.py
We must use `/` separator.
Meson post-process output of pkg-config. If we use `\`,  it miss-interpret it and libdir is broken.
> Fix pkg_config template for icu4c on Windows.

- kiwixbuild/dependencies/icu4c.py
Previous commit was removing the meson_archive.
Fix #723
> Fix extract of meson archive.

- .github/scripts/build_definition.py
- .github/scripts/common.py
- kiwixbuild/dependencies/aria2.py
- kiwixbuild/dependencies/libcurl.py
- kiwixbuild/dependencies/libkiwix.py
- kiwixbuild/dependencies/libmicrohttpd.py
- kiwixbuild/dependencies/pugixml.py
- kiwixbuild/flatpak_builder.py
- kiwixbuild/patches/libmicrohttpd_meson_pkgconfig.patch
- kiwixbuild/versions.py
This PR is:
- building dependencies archive for kiwix-tools and kiwix-desktop projects on windows.
- fix CI and publication of libzim on windows.
Dependencies archive for zim-tools is not made as we need to fix compilation of libmagic on windows first.
Fix https://github.com/kiwix/kiwix-build/issues/466
Fix https://github.com/kiwix/kiwix-build/issues/128
> Setup CI for other projects.

- kiwixbuild/dependencies/libmicrohttpd.py
- kiwixbuild/patches/libmicrohttpd_meson_timeval_tvsec_size.patch
- kiwixbuild/versions.py
Upstream issue is https://github.com/mesonbuild/wrapdb/pull/1625
> Patch libmicrohttpd's meson to correctly detect size of `timeval.tv_sec`

- kiwixbuild/dependencies/libkiwix.py
Now we have fixed libkiwix on Windows, we can activate testing it.
See kiwix/libkiwix#1113
> Activate testing of libkiwix on Windows

- .github/scripts/common.py
On windows, we use prebuild icu and is available as dll.
So we must include those dll in all our archives.
Fix openzim/libzim#923
> Add icu dlls in nightly and releases

- kiwixbuild/dependencies/__init__.py
- kiwixbuild/dependencies/all_dependencies.py
- kiwixbuild/dependencies/boostregex.py
- kiwixbuild/dependencies/docoptcpp.py
- kiwixbuild/dependencies/icu4c.py
- kiwixbuild/patches/docopt_meson_use_boostregex.patch
- kiwixbuild/versions.py
See https://github.com/openzim/zim-tools/pull/425
Compilation with https://github.com/openzim/zim-tools/pull/425 and this dependencies has been validate in this PR #728
> Fix dependencies for zim-tools

- .github/scripts/ensure_base_deps.py
- kiwixbuild/versions.py
Initially we were building all our dependencies in release.
This was simply made by always compiling project using autotool or cmake
in release. As our project are using meson/qmake, all the dependencies
are build in release.
However, with recent port to Windows github CI, we have two problems:
- We have moved almost all buildsystem to meson
- On Windows, we cannot mix debug and release build.
So, when doing a release, do not use base dependencies cache.
This will extend the release workflow as we need to build everything but
at least we should build everything correctly.
> Do not use base_deps when building releases.

- .github/scripts/build_release_nightly.py
There is no reason to publish nightly for all project we try to build in the CI.
We should publish nigthly for same project that we do for releases. (Minus the filter of what have changed since last release)
Fix #743
> Make nigthly CD build and publish only "publishable" project.

- kiwixbuild/dependencies/libmicrohttpd.py
- kiwixbuild/patches/libmicrohttpd_meson_winet6.patch
Should fix kiwix/libkiwix#1144
Under Windows `libmicrohttpd` was being built with support for IPv6 disabled, which - according to debugging - was the main root cause of kiwix/libkiwix#1144. This PR should eliminate that problem.
> Enable IPv6 in meson build of libmicrohttpd under Windows

- kiwixbuild/versions.py
Merging of PR #761 necessitates that the `base_deps` archive for Windows be rebuilt. This is achieved by incrementing `base_deps_meta_version` which will lead to rebuilding of all base dependencies on all platforms.
Once the CI of this PR finishes [base_deps_windows_native_static_08.tar.gz](https://tmp.kiwix.org/ci/base_deps_windows_native_static_08.tar.gz) and its counterparts for other platforms should become available. Then, after this PR is merged, subsequent CI/CD runs will use the new deps archives.
> Bump base_deps_meta_version to rebuild libmicrohttpd

- kiwixbuild/dependencies/libcurl.py
This fixes the libcurl compilation by explicitly disabling PSL and GSS-API for https://github.com/kiwix/kiwix-apple/issues/984
Note that with this there is still an undefined symbol named  `SCDynamicStoreCopyProxies`.
This is apparently [macOS-specific](https://developer.apple.com/documentation/systemconfiguration/1517088-scdynamicstorecopyproxies) and is fixed by linking (dynamically) to `SystemConfiguration.framework`.
This doesn't seem configurable as this function is used [when `CURL_MACOS_CALL_COPYPROXIES`](https://github.com/curl/curl/blob/master/lib/macos.c) is set but this define is not exposed in config but is [set based on target](https://github.com/curl/curl/blob/master/lib/curl_setup.h#L372).
libcurl did not use/call this function in version 7.67.0 which is the one that was …
> Fix missing symbols on CoreKiwix.xcframework

- kiwixbuild/dependencies/base.py
- kiwixbuild/dependencies/kiwix_desktop.py
- kiwixbuild/versions.py
Fixes #757
`base_deps_meta_version` was bumped so that the base dependencies archives for CI workflows are recreated (we need only the Windows flavours of the archives updated but such surgical intervention is not supported).
> Under Windows builds are forced to release mode

- .github/scripts/build_definition.py
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- scripts/create_kiwix-desktop_appImage.sh
Fixes kiwix/kiwix-desktop#1219
Depends on kiwix/container-images#264
A working appimage was created using the updated `scripts/create_kiwix-desktop_appImage.sh` in a docker container build using the following Dockerfile  `kiwix-build_ci/jammy_builder.dockerfile` introduced by kiwix/container-images#264).
> Kiwix desktop jammy appimage

- kiwixbuild/utils.py
`download.kiwix.org/dev/` was deprecated long ago ; this uses the correct address: https://dev.kiwix.org/kiwix-build/
- This is a mandatory fix (old URL not working anymore).
- This doesnt change anything.
Already tested in https://github.com/kiwix/kiwix-build/actions/runs/12142381918
> Fix dev.kiwix.org URL for kiwix-build's own deps

- .github/scripts/common.py
- kiwixbuild/dependencies/base.py
The bug was there since 2018. It's strange that it didn't cause problems with previous releases. The most plausible explanation is that this is the first time when the sources of kiwix-desktop are being published via this procedure.
Should fix the issue with the failure of the [Linux (native_dyn, jammy)](https://github.com/kiwix/kiwix-build/actions/runs/12360372427/job/34495187701) job of the `kiwix-desktop` 2.4.0 release workflow run.
> Fixed a bug in kiwix-desktop's source publishing step

- .github/workflows/cd.yml
In commit 2321717, OS_NAME was introduced to build_definition in order to support jammy + focal.
The Trigger_Docker job was not updated and was to expecting to run on OS_NAME=linux for which there is now line anymore and thus no possibility to trigger
> Fix OS_NAME for Trigger_Docker job in CD

- kiwixbuild/dependencies/kiwix_desktop.py
- kiwixbuild/versions.py
Upgrades flatpak to 6.7, the older supported flatpak baseapp. The biggest challenge was figuring out that `QMAKEPATH` needed to be `/app` instead of `/app/lib` as it is in the 5.15 line. After [discussing](https://github.com/flathub/io.qt.qtwebengine.BaseApp/issues/375) with the flathub io.qt.webengine.BaseApp folks they added this detail to their main README.
> Flatpak uses qt6

- .github/workflows/ci.yml
Once https://github.com/kiwix/kiwix-desktop/pull/1295 is merged, kiwix-build can upgrade to a more recent Qt version. I used 6.4.3 since this is close to the Ubuntu noble version. Its recent without being the newest platform we test on.
> Windows build uses Qt 6.4.3

- kiwixbuild/flatpak_builder.py
Fixes https://github.com/kiwix/kiwix-desktop/issues/1310
> Allow to directly access ZIM file (ready-only) in Kiwix Desktop Flatpak

- kiwixbuild/dependencies/libcurl.py
Should fix kiwix/libkiwix#1180
SSL support has been disabled in our own build of `libcurl` since the very beginning.
One problem with enabling SSL is the CA certificate path that is hardcoded into `libcurl` during the configuration step. Under our Linux build system (Ubuntu) it is set to `/etc/ssl/certs/ca-certificates.crt` but on other distributions of Linux, CA certificates may reside at another location and then https URL won't work.
> Enable SSL support in libcurl

- kiwixbuild/dependencies/tc_android_ndk.py
- kiwixbuild/patches/android-ndk-r21e-linux-x86_64-python3.12+.patch
- kiwixbuild/versions.py
Should fix #808
`distutils` was dropped from Python 3.12. Fortunately, our usage of `android-ndk` only relied on `distutils.dir_util.copy_tree()` in `build/tools/make_standalone_toolchain.py` which
is easy to replace with `shutil.copytree()`. That is done via a small patch.
Note that there are more references to `distutils` in the following files but it looks like our CI/CD flows aren't affected by those:
- `sources/third_party/shaderc/third_party/spirv-tools/utils/generate_registry_tables.py`
- `sources/third_party/vulkan/src/scripts/update_deps.py`
- `prebuilt/linux-x86_64/bin/python2.7-config`
- `prebuilt/linux-x86_64/bin/python-config`
- `prebuilt/linux-x86_64/bin/python2-config`
- various files under `prebuilt/linux-x86_64/lib/python2.7/`
- `python-packages/fastboot/setup.py`
- …
> Enabled android-ndk to work with Python 3.12+

- .github/scripts/build_definition.py
Currently, both jammy and focal publish the native_dyn versions of dependencies for libzim and libkiwix.
This creates concurrent upload issues.
This removes this step for jammy so it gets uploaded only once.
Issue #770
> Dont publish built dependencies on jammy to prevent double archives

- .github/workflows/cd.yml
- .github/workflows/ci.yml
We don't need to install `ninja` anymore because it seems to be part of the base image of the runner. Therefore I have comment-out its installation, also to avoid warnings.
> Comment-out ninja install for macOS

- .github/workflows/cd.yml
- .github/workflows/ci.yml
`kiwix-desktop` is built under Windows only in `native_mixed` config and QT is not required for anything else. Therefore it doesn't make sense to run QT installation in Windows `native_dyn` and `native_static` CI/CD jobs. That will reduce the risk of those jobs failing because of [problems with QT mirrors](https://github.com/kiwix/kiwix-build/issues/816).
> QT is installed only in a windows native_mixed job

- kiwixbuild/dependencies/gumbo.py
- kiwixbuild/versions.py
Gumbo-parser has been forked and has a new maintainer (not Google anymore). Look at https://codeberg.org/gumbo-parser/gumbo-parser/releases
This PR will fix https://github.com/openzim/zim-tools/issues/331
> Use Gumbo-parser version 0.12.1

- kiwixbuild/dependencies/tc_musl.py
- kiwixbuild/utils.py
- kiwixbuild/versions.py
Archives should be put in dev.kiwix.org drive. Since a short time it seems that the musl release server block GitHub IPs. See for example https://github.com/kiwix/kiwix-build/actions/runs/15362522826/job/43231415817
> Rellocate musl archive

- kiwixbuild/buildenv.py
- kiwixbuild/builder.py
- kiwixbuild/configs/android.py
- kiwixbuild/configs/armhf.py
- kiwixbuild/configs/flatpak.py
- kiwixbuild/configs/i586.py
- kiwixbuild/configs/musl.py
- kiwixbuild/configs/native.py
- kiwixbuild/configs/neutral.py
- kiwixbuild/configs/wasm.py
- kiwixbuild/configs/win64.py
- kiwixbuild/packages.py
Adds package profiles for various versions of ubuntu - jammy, noble, oracular, and uses their appropriate versions of Qt. 
When specifying packages, you can now use the LSB `codename` in the `PACKAGE_NAME_MAPPERS` dictionary, giving more control about whether (say) a qt package should be installed as version 5 or 6. For example `ubuntu_jammy_native_dyn` and `ubuntu_noble_native_dyn` are now checked to find the package list. Similarly `debian_bookworm_native_dyn` could be used, but I didn't change any existing package lists.
> Support ubuntu jammy, noble, and oracular with their appropriate qt

- kiwixbuild/versions.py
Attempt to fix https://github.com/kiwix/kiwix-desktop/issues/1404
Not updating the `base_deps_meta_version` number as this should be done anyway soon, once @rgaudin will have fixed https://github.com/kiwix/kiwix-build/issues/852
> Bump-up Flatpak KDE dependency to 6.9

- .github/scripts/common.py
When we merged #850, it was followed by an [issue](https://github.com/kiwix/kiwix-build/actions/runs/18040483724/job/52043376783) because in-PR CD built the dependencies locally and uploaded it but we did not test (run again) the uploaded base_deps.
The problem was that with name change, we were not including in the base_deps the `.{step}_ok` special files that informs kiwix-build to skip those steps (configure, compile, install, test) and was thus failing to configure the first dependency (pugixml) because it did not contain the meson file (supposed to be an empty folder with just those special files).
For this PR, I deleted the macos-15 base deps and [ran it twice](https://github.com/kiwix/kiwix-build/actions/runs/18282882068/) to confirm it's properly fixed.
Fixes #852
> Fixed base_deps for apple_all_static
